### ISSUE TITLE
support for laravel 5.3

### ISSUE THREAD

**Issue by martingg88** [langaner/materialized-path#1]
Does it work for Laravel 5.3? seems like i can't composer require this library for laravel 5.3.

Thanks.

**Comment by langaner** [comment]
Add support 5.3 version. Will test functional for new version soon as possible.

**Comment by martingg88** [comment]
Thank. But try to install by using composer and still fail for requirement not meet for laravel  V5.3.2.

Thank You.

**Comment by langaner** [comment]
I install fresh version of laravel 5.3(5.3.28), add to composer "langaner/materialized-path": "dev-master" and run composer update. Build pass without version compatible errors.

**Comment by martingg88** [comment]
It work for now. Many thanks for your help.

**Comment by langaner** [comment]
you are welcome ))
