### ISSUE TITLE
Alternative active packages?

### ISSUE THREAD

**Issue by patrickomeara** [langaner/materialized-path#3]
It appears this repo has gone stale, can anyone recommend an active materialized path package for Laravel?

**Comment by zjbarg** [comment]
Hi, have you found anything?

**Comment by patrickomeara** [comment]
I started using recursive CTEs in MySQL 8.

I highly recommend https://github.com/staudenmeir/laravel-adjacency-list

**Comment by zjbarg** [comment]
> I started using recursive CTEs in MySQL 8.
> 
> I highly recommend https://github.com/staudenmeir/laravel-adjacency-list

Thank you. You saved me some serious time.

**Comment by patrickomeara** [comment]
Glad I could help.
